plugins:
  - name: vyper
networks:
  custom:
     - name: holesky
       chain_id: 17000
       ecosystem: ethereum
       default_provider: geth
geth:
  ethereum:
    holesky:
      uri: http://localhost:8546
